using LogExpert.Core.Classes.Bookmark;
using LogExpert.Core.Entities;

namespace LogExpert.Persister.Tests.Marker;

[TestFixture]
public class BookmarkMarkerTests
{
    [Test]
    public void GetBookmarkLineNumbers_ReturnsImmutableSnapshotAcrossBookmarkChanges ()
    {
        var provider = new BookmarkDataProvider();
        provider.SetBookmarks(new SortedList<int, Bookmark>
        {
            { 10, new Bookmark(10) },
            { 20, Bookmark.CreateAutoGenerated(20, "auto", "hit") }
        });

        var snapshot = provider.GetBookmarkLineNumbers();

        provider.AddBookmark(new Bookmark(30));
        provider.RemoveBookmarkForLine(10);
        _ = provider.AddBookmarks([new Bookmark(40), Bookmark.CreateAutoGenerated(50, "auto", "hit")]);
        Assert.That(provider.GetBookmarkLineNumbers(), Is.EqualTo(new[] { 20, 30, 40, 50 }));
        provider.SetBookmarks(new SortedList<int, Bookmark>
        {
            { 60, new Bookmark(60) },
            { 70, Bookmark.CreateAutoGenerated(70, "auto", "hit") }
        });
        provider.ClearAllBookmarks();
        Assert.That(provider.GetBookmarkLineNumbers(), Is.Empty);
        provider.SetBookmarks(new SortedList<int, Bookmark>
        {
            { 80, new Bookmark(80) },
            { 90, Bookmark.CreateAutoGenerated(90, "auto", "hit") }
        });
        provider.ShiftBookmarks(10);

        Assert.Multiple(() =>
        {
            Assert.That(provider.GetBookmarkLineNumbers(), Is.EqualTo(new[] { 70, 80 }));
            Assert.That(snapshot, Is.EqualTo(new[] { 10, 20 }));
        });
    }
}