using LogExpert.Core.Classes.Bookmark;

using NUnit.Framework;

using BookmarkEntry = LogExpert.Core.Entities.Bookmark;

namespace LogExpert.Tests.Marker;

[TestFixture]
public class BookmarkMarkerTests
{
    [Test]
    public void GetBookmarkLineNumbers_ReturnsImmutableSnapshotAcrossBookmarkChanges ()
    {
        var provider = new BookmarkDataProvider();
        provider.SetBookmarks(new SortedList<int, BookmarkEntry>
        {
            { 10, new BookmarkEntry(10) },
            { 20, BookmarkEntry.CreateAutoGenerated(20, "auto", "hit") }
        });

        var snapshot = provider.GetBookmarkLineNumbers();

        provider.AddBookmark(new BookmarkEntry(30));
        provider.RemoveBookmarkForLine(10);
        _ = provider.AddBookmarks([new BookmarkEntry(40), BookmarkEntry.CreateAutoGenerated(50, "auto", "hit")]);
        Assert.That(provider.GetBookmarkLineNumbers(), Is.EqualTo(new[] { 20, 30, 40, 50 }));
        provider.SetBookmarks(new SortedList<int, BookmarkEntry>
        {
            { 60, new BookmarkEntry(60) },
            { 70, BookmarkEntry.CreateAutoGenerated(70, "auto", "hit") }
        });
        provider.ClearAllBookmarks();
        Assert.That(provider.GetBookmarkLineNumbers(), Is.Empty);
        provider.SetBookmarks(new SortedList<int, BookmarkEntry>
        {
            { 80, new BookmarkEntry(80) },
            { 90, BookmarkEntry.CreateAutoGenerated(90, "auto", "hit") }
        });
        provider.ShiftBookmarks(10);

        Assert.Multiple(() =>
        {
            Assert.That(provider.GetBookmarkLineNumbers(), Is.EqualTo(new[] { 70, 80 }));
            Assert.That(snapshot, Is.EqualTo(new[] { 10, 20 }));
        });
    }
}