//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogExpert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogExpert.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Arrow_menu_close {
            get {
                object obj = ResourceManager.GetObject("Arrow_menu_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Arrow_menu_open {
            get {
                object obj = ResourceManager.GetObject("Arrow_menu_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_add {
            get {
                object obj = ResourceManager.GetObject("Bookmark_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_added {
            get {
                object obj = ResourceManager.GetObject("Bookmark_added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bookmark_bubbles {
            get {
                object obj = ResourceManager.GetObject("bookmark_bubbles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_manager {
            get {
                object obj = ResourceManager.GetObject("Bookmark_manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_remove {
            get {
                object obj = ResourceManager.GetObject("Bookmark_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmarks {
            get {
                object obj = ResourceManager.GetObject("Bookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check_circle {
            get {
                object obj = ResourceManager.GetObject("Check_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_AccessDeniedExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_AccessDeniedExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing config data: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_ErrorWhileDeserializingConfigData {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_ErrorWhileDeserializingConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system error: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_FileSystemErrorExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_FileSystemErrorExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_UnexpectedErrorExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_UnexpectedErrorExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadingSettings {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings portable mode.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadSettingsPortableMode {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadSettingsPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings standard mode.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadSettingsStandardMode {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadSettingsStandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        public static string ConfigManager_Logger_Info_SavingSettings {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deceased {
            get {
                object obj = ResourceManager.GetObject("Deceased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Favorite {
            get {
                object obj = ResourceManager.GetObject("Favorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap File_open {
            get {
                object obj = ResourceManager.GetObject("File_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder_open {
            get {
                object obj = ResourceManager.GetObject("Folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during add of highlight entry: {0}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_ErrorDuringAddOfHighLightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_ErrorDuringAddOfHighLightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save of save highlight entry: {0}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_ErrorDuringSavingOfHighlightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_ErrorDuringSavingOfHighlightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to access file: {0}, exception: {1}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_FileAccessError {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex value is null or whitespace.
        /// </summary>
        public static string HighlightDialog_RegexError {
            get {
                return ResourceManager.GetString("HighlightDialog_RegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default].
        /// </summary>
        public static string HighlightDialog_UI_DefaultGroupName {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during add of entry.\r\n{0}.
        /// </summary>
        public static string HighlightDialog_UI_ErrorDuringAddOfHighLightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_ErrorDuringAddOfHighLightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save of entry.\r\n{0}.
        /// </summary>
        public static string HighlightDialog_UI_ErrorDuringSavingOfHighlightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_ErrorDuringSavingOfHighlightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (*.json)|*.json|All files (*.*).
        /// </summary>
        public static string HighlightDialog_UI_Export_Filter {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Export_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string HighlightDialog_UI_NewGroup_BaseName {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_NewGroup_BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be imported: {exSettings could not be imported: {0}.
        /// </summary>
        public static string HighlightDialog_UI_SettingsCouldNotBeImported {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_SettingsCouldNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings imported.
        /// </summary>
        public static string HighlightDialog_UI_SettingsImported {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_SettingsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of.
        /// </summary>
        public static string HighlightDialog_UI_Snippet_CopyOf {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Snippet_CopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings to file.
        /// </summary>
        public static string HighlightDialog_UI_Title_ExportSettings {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Title_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not begin restart session. Unable to determine file locker..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotBeginRestartSessionUnableToDetermineFileLocker {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotBeginRestartSessionUnableToDetermineFileLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource.
        /// </summary>
        public static string Lockfinder_Exception_CouldNotListProcessesLockingResource {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotListProcessesLockingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource. Failed to get size of result..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotListProcessesLockingResourceFailedToGetSizeOfResult {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotListProcessesLockingResourceFailedToGetSizeOfResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register resource..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotRegisterResource {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotRegisterResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processes are locking the path specified.
        /// </summary>
        public static string Lockfinder_Exception_NoProcessesAreLockingThePathSpecified {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_NoProcessesAreLockingThePathSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RmEndSession: {0}.
        /// </summary>
        public static string Lockfinder_Trace_RmEndSessionNativeMethodsRmEndSessionHandle {
            get {
                return ResourceManager.GetString("Lockfinder_Trace_RmEndSessionNativeMethodsRmEndSessionHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding window to list.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_AddWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new LogTabWindow.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_CreatingNewWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_CreatingNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last LogTabWindow was closed.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_LastTabWindowClosed {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_LastTabWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files into existing LogTabWindow.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_LoadingFilesIntoLogTab {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_LoadingFilesIntoLogTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No windows left. New created window will be the new &apos;first&apos; GUI window.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_NoWindowsLeftCreatingNewOne {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_NoWindowsLeftCreatingNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing window from list.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_RemoveWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_RemoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first GUI thread window is disposed. Setting a new one..
        /// </summary>
        public static string LogExpertProxy_Logger_Warn_GUIThreadDisposedSettingNewOne {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Warn_GUIThreadDisposedSettingNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {0}: {1}.
        /// </summary>
        public static string Logger_Error_In_Function {
            get {
                return ResourceManager.GetString("Logger_Error_In_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogLover {
            get {
                object obj = ResourceManager.GetObject("LogLover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddBookmarkOverlay() r.Location={0}, width={1}, scroll_offset={2}.
        /// </summary>
        public static string LogWindow_Logger_Debug_AddBookmarkOverlays {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_AddBookmarkOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;GetTimestampForLine({0}) enter.
        /// </summary>
        public static string LogWindow_Logger_Debug_GetTimestampForLineLastLineNumEnter {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_GetTimestampForLineLastLineNumEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTimestampForLine() leave with lineNum={0}.
        /// </summary>
        public static string LogWindow_Logger_Debug_GetTimestampForLineLeaveWithLineNumLastLineNum {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_GetTimestampForLineLeaveWithLineNumLastLineNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventing reload because of recursive calls..
        /// </summary>
        public static string LogWindow_Logger_Debug_PreventingReloadBecauseOfRecursiveCalls {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_PreventingReloadBecauseOfRecursiveCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading invoked..
        /// </summary>
        public static string LogWindow_Logger_Debug_ReloadingInvoked {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_ReloadingInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection changed trigger.
        /// </summary>
        public static string LogWindow_Logger_Debug_SelectionChangedTrigger {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_SelectionChangedTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting columnizer {0}.
        /// </summary>
        public static string LogWindow_Logger_Debug_SettingColumnizer_currentColumnizerGetName {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_SettingColumnizer_currentColumnizerGetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found block: {0}.
        /// </summary>
        public static string LogWindow_Logger_Debug_TestStatistic_DebugInfo_FoundBlock {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_TestStatistic_DebugInfo_FoundBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestStatistic(): i={0} searchLine={1}.
        /// </summary>
        public static string LogWindow_Logger_Debug_TestStatistic_TestStatisticDebugInfo {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_TestStatistic_TestStatisticDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateGrid(): Rollover=true, Rollover offset={0}, currLineNum was {1}, new currLineNum={2}.
        /// </summary>
        public static string LogWindow_Logger_Debug_UpdateGridRolloverTrueRollover {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Debug_UpdateGridRolloverTrueRollover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while clearing filter list: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_ClearFilterList_WhileClearingFilterList {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_ClearFilterList_WhileClearingFilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting temp file {0}: {1}.
        /// </summary>
        public static string LogWindow_Logger_Error_CloseLogWindow_ErrorWhileDeletingTempFile {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_CloseLogWindow_ErrorWhileDeletingTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving persistence: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_ErrorSavingPersistence {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_ErrorSavingPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in selectionChangedTrigger_Signal selcount {0}, Exception: {1}.
        /// </summary>
        public static string LogWindow_Logger_Error_InSelectionChangedTrigger_SignalSelcount {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_InSelectionChangedTrigger_SignalSelcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in UpdateProgress Callback: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_InUpdateProgressCallback {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_InUpdateProgressCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line count of event is: {0}, should be greater than last line count: {1}.
        /// </summary>
        public static string LogWindow_Logger_Error_LineCountOfEventIsShouldBeGreaterThanLastLineCount {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_LineCountOfEventIsShouldBeGreaterThanLastLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading bookmarks: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_LoadingBookmarks {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_LoadingBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading persistence data: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_LoadingPersistenceData {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_LoadingPersistenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error LoadingStarted Callback: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_LoadingStartedCallback {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_LoadingStartedCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while selecting line: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_SelectLine_WhileSelectingLine {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_SelectLine_WhileSelectingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting splitter distance: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_SettingSplitterDistance {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_SettingSplitterDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resizing columns: {0}.
        /// </summary>
        public static string LogWindow_Logger_Error_WhileResizingColumns {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Error_WhileResizingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing window for {0} to {1}.
        /// </summary>
        public static string LogWindow_Logger_Info_AddToTimeSync_SyncingWindow {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_AddToTimeSync_SyncingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temp file {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_CloseLogWindow_DeletingTempFile {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_CloseLogWindow_DeletingTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected MultiFile name list in persistence options.
        /// </summary>
        public static string LogWindow_Logger_Info_DetectedMultiFileNameListInPersistenceOptions {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_DetectedMultiFileNameListInPersistenceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} events in queue.
        /// </summary>
        public static string LogWindow_Logger_Info_EventsInQueue {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_EventsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loading complete..
        /// </summary>
        public static string LogWindow_Logger_Info_FileLoadingComplete {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_FileLoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single threaded filter duration: {0} ms..
        /// </summary>
        public static string LogWindow_Logger_Info_Filter_SingleThreadedFilterDuration {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_Filter_SingleThreadedFilterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished loading..
        /// </summary>
        public static string LogWindow_Logger_Info_FinishedLoading {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_FinishedLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Syncing window for {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_FreeFromTimeSync_DeSyncingWindow {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_FreeFromTimeSync_DeSyncingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got FileSizeChanged event. prevLines:{0}, curr lines: {1}.
        /// </summary>
        public static string LogWindow_Logger_Info_GotFileSizeChangedEventPrevLines0CurrLines1 {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_GotFileSizeChangedEventPrevLines0CurrLines1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling file not found event..
        /// </summary>
        public static string LogWindow_Logger_Info_HandlingFileNotFoundEvent {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_HandlingFileNotFoundEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading logfile: {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_LoadFile_LoadingLogfile {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_LoadFile_LoadingLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked new columnizer &apos;{0}.
        /// </summary>
        public static string LogWindow_Logger_Info_LoadFile_PickedNewColumnizer {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_LoadFile_PickedNewColumnizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadFilesAsMulti: File: {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_LoadFilesAsMulti_FileName {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_LoadFilesAsMulti_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi threaded filter duration: {0} ms..
        /// </summary>
        public static string LogWindow_Logger_Info_MultiThreadedFilter_Duration {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_MultiThreadedFilter_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new File created..
        /// </summary>
        public static string LogWindow_Logger_Info_NewFileCreated {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_NewFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No persistence data for {0} found..
        /// </summary>
        public static string LogWindow_Logger_Info_NoPersistenceDataForFileNameFound {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_NoPersistenceDataForFileNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence data for {0} is outdated. It was discarded..
        /// </summary>
        public static string LogWindow_Logger_Info_PersistenceDataForFileNameIsOutdatedItWasDiscarded {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_PersistenceDataForFileNameIsOutdatedItWasDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing filter view because of reload..
        /// </summary>
        public static string LogWindow_Logger_Info_RefreshingFilterViewBecauseOfReload {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_RefreshingFilterViewBecauseOfReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading file because it has been respawned..
        /// </summary>
        public static string LogWindow_Logger_Info_ReloadingFileBecauseItHasBeenRespawned {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_ReloadingFileBecauseItHasBeenRespawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReloadNewFile(): counter = {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_ReloadNewFileCounter_reloadOverloadCounter {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_ReloadNewFileCounter_reloadOverloadCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetColumnizerInternal(): {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_SetColumnizerInternal {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_SetColumnizerInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit control in logWindow was null.
        /// </summary>
        public static string LogWindow_Logger_Info_StartEditMode_EditControlInLogWindowWasNull {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_StartEditMode_EditControlInLogWindowWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestStatistics() ended.
        /// </summary>
        public static string LogWindow_Logger_Info_TestStatistic_Ended {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_TestStatistic_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestStatistics() called with start line {0}.
        /// </summary>
        public static string LogWindow_Logger_Info_TestStatistic_TestStatisticsCalledWithStartLine {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_TestStatistic_TestStatisticsCalledWithStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelStart: {0}, SelLen: {1}.
        /// </summary>
        public static string LogWindow_Logger_Info_UpdateEditColumnDisplay {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_UpdateEditColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateGrid(): new RowCount={0}.
        /// </summary>
        public static string LogWindow_Logger_Info_UpdateGridNewRowCount {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_UpdateGridNewRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for loading to be complete..
        /// </summary>
        public static string LogWindow_Logger_Info_WaitingForLoadingToBeComplete {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_WaitingForLoadingToBeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for signal.
        /// </summary>
        public static string LogWindow_Logger_Info_WaitingForSignal {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_WaitingForSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeup signal received..
        /// </summary>
        public static string LogWindow_Logger_Info_WakeupSignalReceived {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Info_WakeupSignalReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterRestore(): Columnizer {0} not found.
        /// </summary>
        public static string LogWindow_Logger_Warn_FilterRestore_ColumnizerNameNotFound {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Warn_FilterRestore_ColumnizerNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected issue truncating file: {0}.
        /// </summary>
        public static string LogWindow_Logger_Warn_TryToTruncate_UnexpectedIssueTruncatingFileExMessage {
            get {
                return ResourceManager.GetString("LogWindow_Logger_Warn_TryToTruncate_UnexpectedIssueTruncatingFileExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string LogWindow_UI_ClearFilterList_ResetFilterCounterToZero {
            get {
                return ResourceManager.GetString("LogWindow_UI_ClearFilterList_ResetFilterCounterToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-&gt;Clip.
        /// </summary>
        public static string LogWindow_UI_CopyMarkedLinesToTab_Clip {
            get {
                return ResourceManager.GetString("LogWindow_UI_CopyMarkedLinesToTab_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-&gt;C.
        /// </summary>
        public static string LogWindow_UI_CopyMarkedLinesToTab_Copy {
            get {
                return ResourceManager.GetString("LogWindow_UI_CopyMarkedLinesToTab_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while exporting bookmark list: {0}.
        /// </summary>
        public static string LogWindow_UI_ErrorWhileExportingBookmarkList {
            get {
                return ResourceManager.GetString("LogWindow_UI_ErrorWhileExportingBookmarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while importing bookmark list: {0}.
        /// </summary>
        public static string LogWindow_UI_ErrorWhileImportingBookmarkList {
            get {
                return ResourceManager.GetString("LogWindow_UI_ErrorWhileImportingBookmarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while filtering. Please report to developer: \n\n{0}\n\n{1}.
        /// </summary>
        public static string LogWindow_UI_Filter_ExceptionWhileFiltering {
            get {
                return ResourceManager.GetString("LogWindow_UI_Filter_ExceptionWhileFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv)|*.csv|Bookmark file (*.bmk)|*.bmk.
        /// </summary>
        public static string LogWindow_UI_ImportExportBookmarkList_Filter {
            get {
                return ResourceManager.GetString("LogWindow_UI_ImportExportBookmarkList_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load file\n{0}.
        /// </summary>
        public static string LogWindow_UI_LoadFile_CannotLoadFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_LoadFile_CannotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while saving persistence: {0}.
        /// </summary>
        public static string LogWindow_UI_SavePersistenceData_ErrorWhileSaving {
            get {
                return ResourceManager.GetString("LogWindow_UI_SavePersistenceData_ErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result not found.
        /// </summary>
        public static string LogWindow_UI_SelectLine_SearchResultNotFound {
            get {
                return ResourceManager.GetString("LogWindow_UI_SelectLine_SearchResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression.
        /// </summary>
        public static string LogWindow_UI_StatusLineError_InvalidRegularExpression {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineError_InvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found: {0}.
        /// </summary>
        public static string LogWindow_UI_StatusLineError_NotFound {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started from beginning of file.
        /// </summary>
        public static string LogWindow_UI_StatusLineError_StartedFromBeginningOfFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineError_StartedFromBeginningOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started from end of file.
        /// </summary>
        public static string LogWindow_UI_StatusLineError_StartedFromEndOfFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineError_StartedFromEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_FileNotFound {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter duration: &quot; + ({0}) + &quot; ms..
        /// </summary>
        public static string LogWindow_UI_StatusLineText_Filter_FilterDurationMs {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_Filter_FilterDurationMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering... Press ESC to cancel.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_FilterSearch_Filtering {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_FilterSearch_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching... Press ESC to cancel..
        /// </summary>
        public static string LogWindow_UI_StatusLineText_SearchingPressESCToCancel {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_SearchingPressESCToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected lines.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_SelCountSelectedLines {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_SelCountSelectedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time diff is {0}.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_TimeDiff {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_TimeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncate failed: file is locked by {0}.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_TruncateFailedFileIsLockedByName {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_TruncateFailedFileIsLockedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected issue truncating file.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_UnexpectedIssueTruncatingFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_UnexpectedIssueTruncatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    {0}.
        /// </summary>
        public static string LogWindow_UI_StatusLineText_UpdateEditColumnDisplay {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_UpdateEditColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to temp file... Press ESC to cancel..
        /// </summary>
        public static string LogWindow_UI_StatusLineText_WritePipeToTab_WritingToTempFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusLineText_WritePipeToTab_WritingToTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file....
        /// </summary>
        public static string LogWindow_UI_StatusText_LoadingFile {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusText_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        public static string LogWindow_UI_StatusText_LoadingWithParameter {
            get {
                return ResourceManager.GetString("LogWindow_UI_StatusText_LoadingWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure to close?.
        /// </summary>
        public static string LogWindow_UI_SureToClose {
            get {
                return ResourceManager.GetString("LogWindow_UI_SureToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze left columns until here ({0}).
        /// </summary>
        public static string LogWindow_UI_Text_FreezeLeftColumnsUntilHereGridViewColumns_selectedColHeaderText {
            get {
                return ResourceManager.GetString("LogWindow_UI_Text_FreezeLeftColumnsUntilHereGridViewColumns_selectedColHeaderText" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        public static string LogWindow_UI_Text_Frozen {
            get {
                return ResourceManager.GetString("LogWindow_UI_Text_Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide advanced....
        /// </summary>
        public static string LogWindow_UI_Text_ShowAdvancedFilterPanel_HideAdvanced {
            get {
                return ResourceManager.GetString("LogWindow_UI_Text_ShowAdvancedFilterPanel_HideAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show advanced....
        /// </summary>
        public static string LogWindow_UI_Text_ShowAdvancedFilterPanel_ShowAdvanced {
            get {
                return ResourceManager.GetString("LogWindow_UI_Text_ShowAdvancedFilterPanel_ShowAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some comments in the bookmarks. Really remove bookmarks?.
        /// </summary>
        public static string LogWindow_UI_ThereAreSomeCommentsInTheBookmarksReallyRemoveBookmarks {
            get {
                return ResourceManager.GetString("LogWindow_UI_ThereAreSomeCommentsInTheBookmarksReallyRemoveBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file to save bookmarks into.
        /// </summary>
        public static string LogWindow_UI_Title_ExportBookMarkList {
            get {
                return ResourceManager.GetString("LogWindow_UI_Title_ExportBookMarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file to load bookmarks from.
        /// </summary>
        public static string LogWindow_UI_Title_ImportBookmarkList {
            get {
                return ResourceManager.GetString("LogWindow_UI_Title_ImportBookmarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a comment attached to the bookmark. Really remove the bookmark?.
        /// </summary>
        public static string LogWindow_UI_ToggleBookmark_ThereCommentAttachedRemoveIt {
            get {
                return ResourceManager.GetString("LogWindow_UI_ToggleBookmark_ThereCommentAttachedRemoveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt;F.
        /// </summary>
        public static string LogWindow_UI_WriteFilterToTab_NamePrefix_ForFilter {
            get {
                return ResourceManager.GetString("LogWindow_UI_WriteFilterToTab_NamePrefix_ForFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string PaintHelper_HeaderText_LineNumberColumn {
            get {
                return ResourceManager.GetString("PaintHelper_HeaderText_LineNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pro_Filter {
            get {
                object obj = ResourceManager.GetObject("Pro_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpcClientChannel error, giving up: {0}.
        /// </summary>
        public static string Program_Logger_Error_IPCChannel_ClientError {
            get {
                return ResourceManager.GetString("Program_Logger_Error_IPCChannel_ClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpcClientChannel error: {0}.
        /// </summary>
        public static string Program_Logger_Error_IPCChannel_ClientError_Default {
            get {
                return ResourceManager.GetString("Program_Logger_Error_IPCChannel_ClientError_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutex error, giving up: {0}.
        /// </summary>
        public static string Program_Logger_Error_MutexError {
            get {
                return ResourceManager.GetString("Program_Logger_Error_MutexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payload command: null.
        /// </summary>
        public static string Program_Logger_Error_Payload_InvalidCommand {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Payload_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout connecting to pipe server.
        /// </summary>
        public static string Program_Logger_Error_Pipe_TimeoutException {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Pipe_TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown IPC Message Type: {0}; with payload: {1}.
        /// </summary>
        public static string Program_Logger_Error_Pipe_UnkownIPCMessage {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Pipe_UnkownIPCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Error_Pipe_IOException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Error_Pipe_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe server error: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_CommonError {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_InvalidOperationException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found.
        /// </summary>
        public static string Program_UI_Error_ConfigFileNotFound {
            get {
                return ResourceManager.GetString("Program_UI_Error_ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient system rights for LogExpert. Maybe you have started it from a network drive. Please start LogExpert from a local drive.\n ({0}).
        /// </summary>
        public static string Program_UI_Error_InsufficiantRights {
            get {
                return ResourceManager.GetString("Program_UI_Error_InsufficiantRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open connection to first instance ({0}).
        /// </summary>
        public static string Program_UI_Error_Pipe_CannotConnectToFirstInstance {
            get {
                return ResourceManager.GetString("Program_UI_Error_Pipe_CannotConnectToFirstInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Restart_alt {
            get {
                object obj = ResourceManager.GetObject("Restart_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogExpert.
        /// </summary>
        public static string Title_LogExpert {
            get {
                return ResourceManager.GetString("Title_LogExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogExpert Error.
        /// </summary>
        public static string Title_LogExpert_Error {
            get {
                return ResourceManager.GetString("Title_LogExpert_Error", resourceCulture);
            }
        }
    }
}
