//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogExpert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogExpert.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Arrow_menu_close {
            get {
                object obj = ResourceManager.GetObject("Arrow_menu_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Arrow_menu_open {
            get {
                object obj = ResourceManager.GetObject("Arrow_menu_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_add {
            get {
                object obj = ResourceManager.GetObject("Bookmark_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_added {
            get {
                object obj = ResourceManager.GetObject("Bookmark_added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bookmark_bubbles {
            get {
                object obj = ResourceManager.GetObject("bookmark_bubbles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_manager {
            get {
                object obj = ResourceManager.GetObject("Bookmark_manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmark_remove {
            get {
                object obj = ResourceManager.GetObject("Bookmark_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmarks {
            get {
                object obj = ResourceManager.GetObject("Bookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Check_circle {
            get {
                object obj = ResourceManager.GetObject("Check_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_AccessDeniedExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_AccessDeniedExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing config data: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_ErrorWhileDeserializingConfigData {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_ErrorWhileDeserializingConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system error: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_FileSystemErrorExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_FileSystemErrorExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        public static string ConfigManager_Logger_Error_UnexpectedErrorExMessage {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Error_UnexpectedErrorExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadingSettings {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings portable mode.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadSettingsPortableMode {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadSettingsPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings standard mode.
        /// </summary>
        public static string ConfigManager_Logger_Info_LoadSettingsStandardMode {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_LoadSettingsStandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        public static string ConfigManager_Logger_Info_SavingSettings {
            get {
                return ResourceManager.GetString("ConfigManager_Logger_Info_SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deceased {
            get {
                object obj = ResourceManager.GetObject("Deceased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Favorite {
            get {
                object obj = ResourceManager.GetObject("Favorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap File_open {
            get {
                object obj = ResourceManager.GetObject("File_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder_open {
            get {
                object obj = ResourceManager.GetObject("Folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during add of highlight entry: {0}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_ErrorDuringAddOfHighLightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_ErrorDuringAddOfHighLightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save of save highlight entry: {0}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_ErrorDuringSavingOfHighlightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_ErrorDuringSavingOfHighlightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to access file: {0}, exception: {1}.
        /// </summary>
        public static string HighlightDialog_Logger_Error_FileAccessError {
            get {
                return ResourceManager.GetString("HighlightDialog_Logger_Error_FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex value is null or whitespace.
        /// </summary>
        public static string HighlightDialog_RegexError {
            get {
                return ResourceManager.GetString("HighlightDialog_RegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default].
        /// </summary>
        public static string HighlightDialog_UI_DefaultGroupName {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during add of entry.\r\n{0}.
        /// </summary>
        public static string HighlightDialog_UI_ErrorDuringAddOfHighLightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_ErrorDuringAddOfHighLightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save of entry.\r\n{0}.
        /// </summary>
        public static string HighlightDialog_UI_ErrorDuringSavingOfHighlightEntry {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_ErrorDuringSavingOfHighlightEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (*.json)|*.json|All files (*.*).
        /// </summary>
        public static string HighlightDialog_UI_Export_Filter {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Export_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string HighlightDialog_UI_NewGroup_BaseName {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_NewGroup_BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be imported: {exSettings could not be imported: {0}.
        /// </summary>
        public static string HighlightDialog_UI_SettingsCouldNotBeImported {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_SettingsCouldNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings imported.
        /// </summary>
        public static string HighlightDialog_UI_SettingsImported {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_SettingsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of.
        /// </summary>
        public static string HighlightDialog_UI_Snippet_CopyOf {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Snippet_CopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings to file.
        /// </summary>
        public static string HighlightDialog_UI_Title_ExportSettings {
            get {
                return ResourceManager.GetString("HighlightDialog_UI_Title_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not begin restart session. Unable to determine file locker..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotBeginRestartSessionUnableToDetermineFileLocker {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotBeginRestartSessionUnableToDetermineFileLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource.
        /// </summary>
        public static string Lockfinder_Exception_CouldNotListProcessesLockingResource {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotListProcessesLockingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource. Failed to get size of result..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotListProcessesLockingResourceFailedToGetSizeOfResult {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotListProcessesLockingResourceFailedToGetSizeOfResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register resource..
        /// </summary>
        public static string Lockfinder_Exception_CouldNotRegisterResource {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_CouldNotRegisterResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processes are locking the path specified.
        /// </summary>
        public static string Lockfinder_Exception_NoProcessesAreLockingThePathSpecified {
            get {
                return ResourceManager.GetString("Lockfinder_Exception_NoProcessesAreLockingThePathSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RmEndSession: {0}.
        /// </summary>
        public static string Lockfinder_Trace_RmEndSessionNativeMethodsRmEndSessionHandle {
            get {
                return ResourceManager.GetString("Lockfinder_Trace_RmEndSessionNativeMethodsRmEndSessionHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding window to list.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_AddWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new LogTabWindow.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_CreatingNewWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_CreatingNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last LogTabWindow was closed.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_LastTabWindowClosed {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_LastTabWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files into existing LogTabWindow.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_LoadingFilesIntoLogTab {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_LoadingFilesIntoLogTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No windows left. New created window will be the new &apos;first&apos; GUI window.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_NoWindowsLeftCreatingNewOne {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_NoWindowsLeftCreatingNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing window from list.
        /// </summary>
        public static string LogExpertProxy_Logger_Info_RemoveWindow {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Info_RemoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first GUI thread window is disposed. Setting a new one..
        /// </summary>
        public static string LogExpertProxy_Logger_Warn_GUIThreadDisposedSettingNewOne {
            get {
                return ResourceManager.GetString("LogExpertProxy_Logger_Warn_GUIThreadDisposedSettingNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogLover {
            get {
                object obj = ResourceManager.GetObject("LogLover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string PaintHelper_HeaderText_LineNumberColumn {
            get {
                return ResourceManager.GetString("PaintHelper_HeaderText_LineNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pro_Filter {
            get {
                object obj = ResourceManager.GetObject("Pro_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpcClientChannel error, giving up: {0}.
        /// </summary>
        public static string Program_Logger_Error_IPCChannel_ClientError {
            get {
                return ResourceManager.GetString("Program_Logger_Error_IPCChannel_ClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpcClientChannel error: {0}.
        /// </summary>
        public static string Program_Logger_Error_IPCChannel_ClientError_Default {
            get {
                return ResourceManager.GetString("Program_Logger_Error_IPCChannel_ClientError_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutex error, giving up: {0}.
        /// </summary>
        public static string Program_Logger_Error_MutexError {
            get {
                return ResourceManager.GetString("Program_Logger_Error_MutexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payload command: null.
        /// </summary>
        public static string Program_Logger_Error_Payload_InvalidCommand {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Payload_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout connecting to pipe server.
        /// </summary>
        public static string Program_Logger_Error_Pipe_TimeoutException {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Pipe_TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown IPC Message Type: {0}; with payload: {1}.
        /// </summary>
        public static string Program_Logger_Error_Pipe_UnkownIPCMessage {
            get {
                return ResourceManager.GetString("Program_Logger_Error_Pipe_UnkownIPCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Error_Pipe_IOException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Error_Pipe_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe server error: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_CommonError {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_InvalidOperationException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access while connecting to the pipe server: {0}.
        /// </summary>
        public static string Program_Logger_Warn_Pipe_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Program_Logger_Warn_Pipe_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found.
        /// </summary>
        public static string Program_UI_Error_ConfigFileNotFound {
            get {
                return ResourceManager.GetString("Program_UI_Error_ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient system rights for LogExpert. Maybe you have started it from a network drive. Please start LogExpert from a local drive.\n ({0}).
        /// </summary>
        public static string Program_UI_Error_InsufficiantRights {
            get {
                return ResourceManager.GetString("Program_UI_Error_InsufficiantRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open connection to first instance ({0}).
        /// </summary>
        public static string Program_UI_Error_Pipe_CannotConnectToFirstInstance {
            get {
                return ResourceManager.GetString("Program_UI_Error_Pipe_CannotConnectToFirstInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Restart_alt {
            get {
                object obj = ResourceManager.GetObject("Restart_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogExpert.
        /// </summary>
        public static string Title_LogExpert {
            get {
                return ResourceManager.GetString("Title_LogExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogExpert Error.
        /// </summary>
        public static string Title_LogExpert_Error {
            get {
                return ResourceManager.GetString("Title_LogExpert_Error", resourceCulture);
            }
        }
    }
}
